DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_register;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_log_in;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_recovery;