DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_register;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_log_in;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_blocks_recovery;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_billing_types;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_billing_accounts;
DROP TABLE IF EXISTS {$DBPREFIX$}{$PACKAGENAME$}_{$MODULENAME$}_billing_transactions;